### ISSUE TITLE
Error while installing via pip

### ISSUE THREAD

**Issue by xandykati98** [themis-ai/capsa#120]
`pip install capsa`

`
Collecting capsa
  Using cached capsa-0.1.4.tar.gz (48 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\xandy\AppData\Local\Temp\pip-install-4fbexyn0\capsa_9fd1f598a5a64870b4ab53d71cc69117\setup.py", line 8, in <module>
          readme = readme_file.read()
        File "C:\Users\xandy\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 
23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 873: character maps to 
<undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`

**Comment by egesko** [comment]
Looks like the error is happening when the `setup.py` is trying to decode repo's README file to include it in package's metadata. More concretely, this might be happening because of this reason:

The README file contains non-ASCII characters that the `cp1252` encoding cannot decode. The default encoding on Windows systems is usually `cp1252`, which seems to be not compatible with the encoding used by the capsa.

Possible fix:

Include a default encoding inside `setup.py` when opening README FILE:

```
with open('README.md',encoding="utf-8") as readme_file:
    readme = readme_file.read()
```

Thank you for bringing this to our attention. I will address this issue with **high priority** to make sure the package is compatible with windows systems.

**Comment by egesko** [comment]
[Here's the stackoverflow page](https://stackoverflow.com/questions/26324622/what-characters-do-not-directly-map-from-cp1252-to-utf-8) that explains the issue in more detail.
